# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/willb/Vaults/Personal/DevLab/ggml/ggml-viz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/willb/Vaults/Personal/DevLab/ggml/ggml-viz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/willb/Vaults/Personal/DevLab/ggml/ggml-viz/CMakeFiles /Users/willb/Vaults/Personal/DevLab/ggml/ggml-viz//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/willb/Vaults/Personal/DevLab/ggml/ggml-viz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_minimal_hooks

# Build rule for target.
test_minimal_hooks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_minimal_hooks
.PHONY : test_minimal_hooks

# fast build rule for target.
test_minimal_hooks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_minimal_hooks.dir/build.make CMakeFiles/test_minimal_hooks.dir/build
.PHONY : test_minimal_hooks/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f third_party/CMakeFiles/imgui.dir/build.make third_party/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f third_party/glfw/CMakeFiles/uninstall.dir/build.make third_party/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f third_party/glfw/src/CMakeFiles/glfw.dir/build.make third_party/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f third_party/glfw/src/CMakeFiles/update_mappings.dir/build.make third_party/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named ggml_hook

# Build rule for target.
ggml_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_hook
.PHONY : ggml_hook

# fast build rule for target.
ggml_hook/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ggml_hook.dir/build.make src/CMakeFiles/ggml_hook.dir/build
.PHONY : ggml_hook/fast

#=============================================================================
# Target rules for targets named ggml_utils

# Build rule for target.
ggml_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_utils
.PHONY : ggml_utils

# fast build rule for target.
ggml_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ggml_utils.dir/build.make src/CMakeFiles/ggml_utils.dir/build
.PHONY : ggml_utils/fast

#=============================================================================
# Target rules for targets named ggml_frontend

# Build rule for target.
ggml_frontend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_frontend
.PHONY : ggml_frontend

# fast build rule for target.
ggml_frontend/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ggml_frontend.dir/build.make src/CMakeFiles/ggml_frontend.dir/build
.PHONY : ggml_frontend/fast

#=============================================================================
# Target rules for targets named ggml_viz_hook

# Build rule for target.
ggml_viz_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_viz_hook
.PHONY : ggml_viz_hook

# fast build rule for target.
ggml_viz_hook/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ggml_viz_hook.dir/build.make src/CMakeFiles/ggml_viz_hook.dir/build
.PHONY : ggml_viz_hook/fast

#=============================================================================
# Target rules for targets named ggml-viz

# Build rule for target.
ggml-viz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-viz
.PHONY : ggml-viz

# fast build rule for target.
ggml-viz/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ggml-viz.dir/build.make src/CMakeFiles/ggml-viz.dir/build
.PHONY : ggml-viz/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ggml/src/CMakeFiles/ggml-base.dir/build.make third_party/ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ggml/src/CMakeFiles/ggml.dir/build.make third_party/ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ggml/src/CMakeFiles/ggml-cpu.dir/build.make third_party/ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named ggml-blas

# Build rule for target.
ggml-blas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-blas
.PHONY : ggml-blas

# fast build rule for target.
ggml-blas/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build.make third_party/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build
.PHONY : ggml-blas/fast

#=============================================================================
# Target rules for targets named ggml_hook_test

# Build rule for target.
ggml_hook_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_hook_test
.PHONY : ggml_hook_test

# fast build rule for target.
ggml_hook_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ggml_hook_test.dir/build.make tests/CMakeFiles/ggml_hook_test.dir/build
.PHONY : ggml_hook_test/fast

#=============================================================================
# Target rules for targets named test_ggml_hook

# Build rule for target.
test_ggml_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ggml_hook
.PHONY : test_ggml_hook

# fast build rule for target.
test_ggml_hook/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ggml_hook.dir/build.make tests/CMakeFiles/test_ggml_hook.dir/build
.PHONY : test_ggml_hook/fast

#=============================================================================
# Target rules for targets named test_trace_reader

# Build rule for target.
test_trace_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_trace_reader
.PHONY : test_trace_reader

# fast build rule for target.
test_trace_reader/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_trace_reader.dir/build.make tests/CMakeFiles/test_trace_reader.dir/build
.PHONY : test_trace_reader/fast

test_minimal_hooks.o: test_minimal_hooks.c.o
.PHONY : test_minimal_hooks.o

# target to build an object file
test_minimal_hooks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_minimal_hooks.dir/build.make CMakeFiles/test_minimal_hooks.dir/test_minimal_hooks.c.o
.PHONY : test_minimal_hooks.c.o

test_minimal_hooks.i: test_minimal_hooks.c.i
.PHONY : test_minimal_hooks.i

# target to preprocess a source file
test_minimal_hooks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_minimal_hooks.dir/build.make CMakeFiles/test_minimal_hooks.dir/test_minimal_hooks.c.i
.PHONY : test_minimal_hooks.c.i

test_minimal_hooks.s: test_minimal_hooks.c.s
.PHONY : test_minimal_hooks.s

# target to generate assembly for a file
test_minimal_hooks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_minimal_hooks.dir/build.make CMakeFiles/test_minimal_hooks.dir/test_minimal_hooks.c.s
.PHONY : test_minimal_hooks.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-blas"
	@echo "... ggml-cpu"
	@echo "... ggml-viz"
	@echo "... ggml_frontend"
	@echo "... ggml_hook"
	@echo "... ggml_hook_test"
	@echo "... ggml_utils"
	@echo "... ggml_viz_hook"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... test_ggml_hook"
	@echo "... test_minimal_hooks"
	@echo "... test_trace_reader"
	@echo "... test_minimal_hooks.o"
	@echo "... test_minimal_hooks.i"
	@echo "... test_minimal_hooks.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

